/* ============================================================
   PH1 — CONTENT FILE
   This file is auto-generated by sync_videos.py from videos.xlsx.
   DO NOT EDIT THIS FILE BY HAND — any changes here get overwritten
   the next time the sync script runs. Edit videos.xlsx instead, then
   run: python3 sync_videos.py
   ============================================================ */

const SITE = {
  title: "PH1",
  tagline: "One Channel. Your Voice.",
  categoryOrder: [
    "Season 2026-27",
    "Critically Acclaimed",
    "Segments & Highlights",
    "Student Films & Projects",
    "Archives"
  ],
  archiveCategories: ["Archives"]
};

const VIDEOS = [
  { vimeoId: "1216821480", category: "Critically Acclaimed" },
  { vimeoId: "1216821501", category: "Critically Acclaimed" },
  { vimeoId: "1216821533", category: "Critically Acclaimed" },
  { vimeoId: "1216821494", category: "Critically Acclaimed" },
  { vimeoId: "1216821457", category: "Critically Acclaimed" },
  { vimeoId: "1216821582", category: "Critically Acclaimed" },
  { vimeoId: "1216712426", category: "Segments & Highlights" },
  { vimeoId: "1216821429", category: "Segments & Highlights" },
  { vimeoId: "1216821427", category: "Segments & Highlights" },
  { vimeoId: "1216821428", category: "Segments & Highlights" },
  { vimeoId: "1216821504", category: "Segments & Highlights" },
  { vimeoId: "1216821503", category: "Segments & Highlights" },
  { vimeoId: "1216712429", category: "Archives", featured: true },
  { vimeoId: "1216712427", category: "Archives" },
  { vimeoId: "1216821487", category: "Archives" },
];
