#!/usr/bin/env python3
"""
PH1 — Excel-to-site sync script.

What this does:
  1. Reads videos.xlsx (in this same folder)
  2. Regenerates data.js from those rows
  3. Commits and pushes the change to GitHub

Run it with:
    python3 sync_videos.py

You should basically never need to read the code below this comment —
this file is meant to be run, not edited. If something needs to
change about how it works, ask Claude Code to modify it for you.
"""

import re
import subprocess
import sys
import json
from pathlib import Path

try:
    from openpyxl import load_workbook
except ImportError:
    print("Missing a required package. Run this first, then try again:")
    print("    pip3 install openpyxl")
    sys.exit(1)

REPO_DIR = Path(__file__).resolve().parent
EXCEL_PATH = REPO_DIR / "videos.xlsx"
DATA_JS_PATH = REPO_DIR / "data.js"

# This part rarely changes — it's your site's overall settings, not
# individual videos. If you ever want to rename a category everywhere,
# rename it here (and in the matching cells in videos.xlsx).
SITE_BLOCK = """/* ============================================================
   PH1 — CONTENT FILE
   This file is auto-generated by sync_videos.py from videos.xlsx.
   DO NOT EDIT THIS FILE BY HAND — any changes here get overwritten
   the next time the sync script runs. Edit videos.xlsx instead, then
   run: python3 sync_videos.py
   ============================================================ */

const SITE = {
  title: "PH1",
  tagline: "One Channel. Your Voice.",
  categoryOrder: [
    "Season 2026-27",
    "Critically Acclaimed",
    "Segments & Highlights",
    "Student Films & Projects",
    "Archives"
  ],
  archiveCategories: ["Archives"]
};

const VIDEOS = [
"""


def extract_vimeo_id(value):
    """Pulls the numeric video ID out of a pasted Vimeo link, or accepts
    a bare ID typed directly."""
    if value is None:
        return None
    text = str(value).strip()
    match = re.search(r"(\d{6,})", text)
    return match.group(1) if match else None


def parse_bool(value):
    if value is None:
        return False
    return str(value).strip().lower() in ("true", "yes", "1", "x", "y")


def js_string(value):
    """Safely render a Python string as a JS string literal (handles
    quotes, apostrophes, etc. without breaking the file)."""
    return json.dumps(str(value))


def build_entry(row_num, link, category, featured, title, description, air_date, thumbnail):
    vimeo_id = extract_vimeo_id(link)
    category = str(category).strip() if category else None

    if not vimeo_id:
        return None, f"row {row_num}: couldn't find a Vimeo ID in '{link}'"
    if not category:
        return None, f"row {row_num}: missing a category"

    parts = [f'vimeoId: {js_string(vimeo_id)}', f'category: {js_string(category)}']

    if parse_bool(featured):
        parts.append("featured: true")
    if title and str(title).strip():
        parts.append(f"title: {js_string(title)}")
    if description and str(description).strip():
        parts.append(f"description: {js_string(description)}")
    if air_date and str(air_date).strip():
        # Excel sometimes hands back a datetime object for date-formatted
        # cells rather than plain text — normalize either case to YYYY-MM-DD.
        if hasattr(air_date, "strftime"):
            air_date_str = air_date.strftime("%Y-%m-%d")
        else:
            air_date_str = str(air_date).strip()
        parts.append(f"airDate: {js_string(air_date_str)}")
    if thumbnail and str(thumbnail).strip():
        parts.append(f"thumbnail: {js_string(thumbnail)}")

    return "  { " + ", ".join(parts) + " },", None


def main():
    # Pull first, always — this matters if you're syncing from more than
    # one computer (e.g. a laptop and a school desktop). Without this,
    # editing videos.xlsx on two machines without syncing in between can
    # cause a conflict when pushing. Pulling first means you're always
    # starting from the latest version, on either device.
    pull = subprocess.run(["git", "pull"], cwd=REPO_DIR, capture_output=True, text=True)
    if pull.returncode != 0:
        print("Couldn't pull the latest version from GitHub before syncing:")
        print(pull.stdout + pull.stderr)
        print("\nFix whatever this is describing, then run this script again.")
        sys.exit(1)

    if not EXCEL_PATH.exists():
        print(f"Can't find videos.xlsx in {REPO_DIR}")
        print("Make sure it's saved in the same folder as this script.")
        sys.exit(1)

    wb = load_workbook(EXCEL_PATH, data_only=True)
    ws = wb.active

    entries = []
    warnings = []

    for row_num, row in enumerate(ws.iter_rows(min_row=2, values_only=True), start=2):
        if not row or all(cell is None for cell in row):
            continue  # blank row, skip quietly

        link = row[0] if len(row) > 0 else None
        category = row[1] if len(row) > 1 else None
        featured = row[2] if len(row) > 2 else None
        title = row[3] if len(row) > 3 else None
        description = row[4] if len(row) > 4 else None
        air_date = row[5] if len(row) > 5 else None
        thumbnail = row[6] if len(row) > 6 else None

        entry, warning = build_entry(row_num, link, category, featured, title, description, air_date, thumbnail)
        if entry:
            entries.append(entry)
        if warning:
            warnings.append(warning)

    if warnings:
        print("Skipped some rows — fix these in videos.xlsx and run again:")
        for w in warnings:
            print("  - " + w)

    if not entries:
        print("No valid rows found in videos.xlsx. Nothing was changed.")
        sys.exit(1)

    content = SITE_BLOCK + "\n".join(entries) + "\n];\n"
    DATA_JS_PATH.write_text(content, encoding="utf-8")
    print(f"data.js updated with {len(entries)} video(s).")

    # ---- commit + push ----
    subprocess.run(["git", "add", "data.js"], cwd=REPO_DIR, check=True)

    commit = subprocess.run(
        ["git", "commit", "-m", "Update videos from spreadsheet"],
        cwd=REPO_DIR, capture_output=True, text=True
    )
    combined_output = commit.stdout + commit.stderr
    if commit.returncode != 0:
        if "nothing to commit" in combined_output.lower():
            print("No changes since the last sync — site already matches the spreadsheet.")
            return
        print("Something went wrong committing:")
        print(combined_output)
        sys.exit(1)

    push = subprocess.run(["git", "push"], cwd=REPO_DIR, capture_output=True, text=True)
    if push.returncode != 0:
        print("Commit succeeded locally, but the push to GitHub failed:")
        print(push.stdout + push.stderr)
        print("\nIf this mentions authentication, you likely need to complete the")
        print("one-time GitHub sign-in step described in SETUP.md.")
        sys.exit(1)

    print("Pushed to GitHub! The live site will update in about a minute.")


if __name__ == "__main__":
    main()
